sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
cache: cargo
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo test --bin stevia
addons:
  apt:
    packages:
    - binutils-dev 
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libiberty-dev
    - cmake
    - gcc
    - zlib1g-dev 
after_success:
  - |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master &&
    cargo clean &&
    cargo test --no-run --features "yaml unstable" &&
    for file in target/debug/*-*; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo --verify "target/cov/$(basename $file)" "$file"; done &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --merge target/cov target/cov/* &&
    echo "Uploaded code coverage"